### ISSUE TITLE
automate generation/deployment of docs to GitHub Pages

### ISSUE THREAD

**Issue by dmalan** [cs50/libcs50-java#20]
http://cs50.github.io/libcs50-java/edu/harvard/CS50.html

**Comment by dmalan** [comment]
I just manually pushed latest docs to `gh-pages`, fyi.

**Comment by kzidane** [comment]
You didn't have to. Automatically [deploys](https://github.com/cs50/libcs50-java/blob/develop/.travis.yml#L4-L12) when we merge into master :stuck_out_tongue:

**Comment by dmalan** [comment]
Too efficient!
