### ISSUE TITLE
requires Java 8

### ISSUE THREAD

**Issue by dmalan** [cs50/libcs50-java#5]
While [Java 8](https://docs.oracle.com/javase/8/docs/api/java/lang/Double.html) has `Double.isFinite`, [Java 7](https://docs.oracle.com/javase/7/docs/api/java/lang/Double.html) unfortunately doesn't. With CS50 IDE still on Ubuntu 14.04 (and CS50 CLI similarly fixed at Ubutu 14.04 until CS50 IDE changes), building `edu.harvard.CS50` yields:

```
$ javac -d build src/edu/harvard/CS50.java 
src/edu/harvard/CS50.java:122: error: cannot find symbol
                    if (Double.isFinite(d) && d < Double.MAX_VALUE)
                              ^
  symbol:   method isFinite(double)
  location: class Double
src/edu/harvard/CS50.java:162: error: cannot find symbol
                    if (Float.isFinite(f) && f < Float.MAX_VALUE)
                             ^
  symbol:   method isFinite(float)
  location: class Float
2 errors
make: *** [build] Error 1
```

**Comment by kzidane** [comment]
fixed per https://github.com/cs50/lib50-java/commit/7e639b9c423fff0726539e0275058eed4a3ce21c! see [Double.isInfinite()](http://docs.oracle.com/javase/7/docs/api/java/lang/Double.html#isInfinite%28%29) and [Float.isInfinite()](https://docs.oracle.com/javase/7/docs/api/java/lang/Float.html#isInfinite%28%29)!
