### ISSUE TITLE
test whether getDouble and getFloat accept just `.` as input

### ISSUE THREAD

**Issue by dmalan** [cs50/libcs50-java#7]

**Comment by kzidane** [comment]
Nope. Caught by [`parseDouble`](https://docs.oracle.com/javase/7/docs/api/java/lang/Double.html#parseDouble%28java.lang.String%29) and [`parseFloat`](https://docs.oracle.com/javase/7/docs/api/java/lang/Float.html#parseFloat%28java.lang.String%29) respectively.

**Comment by dmalan** [comment]
Thanks!
