### ISSUE TITLE
disable buffering of stdout, stderr

### ISSUE THREAD

**Issue by dmalan** [cs50/libcs50-java#8]

**Comment by kzidane** [comment]
Hmm, not sure if there's an easy way to achieve this in Java. The auto-flushing state of [`System.err`](https://docs.oracle.com/javase/7/docs/api/java/lang/System.html#err) and [`System.out`](https://docs.oracle.com/javase/7/docs/api/java/lang/System.html#out) doesn't even seem to be well-defined.

We can probably guarantee that for the CS50 library methods by explicitly flushing after printing `Retry:`, but the only way I can think of, now, to get around this, in general, is to define our own printing methods that forcibly flush after printing, and get students to use these methods instead, which doesn't feel like a good idea.

**Comment by dmalan** [comment]
Could we use
http://docs.oracle.com/javase/6/docs/api/java/lang/System.html#setOut%28java.io.PrintStream%29
and reconfigure System.out to use an unbuffered PrintStream?

**Comment by kzidane** [comment]
In this case, assuming we managed to enable [`autoFlush`](https://docs.oracle.com/javase/7/docs/api/java/io/PrintStream.html#PrintStream%28java.io.OutputStream,%20boolean%29) for `err``out`, there would still be no guarantee for the `print` methods to immediately flush? Per `PrintStream`'s documentation

> the output buffer will be flushed whenever a `byte` array is written, one of the `println` methods is invoked, or a newline character or byte (`'\n'`) is written

**Comment by dmalan** [comment]
What if we do something like http://www.thecodingforums.com/threads/a-java-io-question-disable-line-buffering-of-printstream.390477/ with a `size` of `1`, https://docs.oracle.com/javase/7/docs/api/java/io/BufferedOutputStream.html#BufferedOutputStream(java.io.OutputStream,%20int)?

CC @glennholloway

**Comment by kzidane** [comment]
Promising! Will try.

**Comment by kzidane** [comment]
@dmalan, tried

``` java
// disable buffering on stderr and stdout
static {
    // stderr
    FileOutputStream fderr = new FileOutputStream(FileDescriptor.err);

    // stdout
    FileOutputStream fdout = new FileOutputStream(FileDescriptor.out);

    // stderr buffer of size 1
    BufferedOutputStream errBuf = new BufferedOutputStream(fderr, 1);

    // stdout buffer of size 1
    BufferedOutputStream outBuf = new BufferedOutputStream(fdout, 1);

    // add more features and functionality to stderr and stdout
    PrintStream errStream = new PrintStream(errBuf);
    PrintStream outStream = new PrintStream(outBuf); 

    // update stderr and stderr
    System.setErr(errStream);
    System.setOut(outStream);
}
```

and seems to work, but only when the CS50 class is initialized per [12.4.1. When Initialization Occurs](http://docs.oracle.com/javase/specs/jls/se7/html/jls-12.html#jls-12.4.1)

> A class or interface type T will be initialized immediately before the first occurrence of any one of the following:
> - T is a class and an instance of T is created.
> - T is a class and a static method declared by T is invoked.
> - A static field declared by T is assigned.
> - A static field declared by T is used and the field is not a constant variable (§4.12.4).
> - T is a top level class (§7.6), and an assert statement (§14.10) lexically nested within T (§8.1.3) is executed.

...



> **A class or interface will not be initialized under any other circumstance.**

I don't think this is what we want, so looking for other ways to implement this.

Relatively, though, we're now certain that automatic line buffering is enabled for `System.out`, at least, per this [article](http://www.oracle.com/technetwork/articles/javase/perftuning-137844.html#Buffering).

Interestingly, there seems to be inconsistency in the implementation of `PrintStream` both in [OpenJDK](https://bugs.openjdk.java.net/browse/JDK-8025883) and the JDK installed in the CS50 IDE causing every call to `print` to flush. Experienced this while testing (which made it quite difficult to see whether the code above makes any difference, but indeed increasing the buffer size shows that the streams were reset correctly).

I don't think there's a way to have the code above execute just by importing `edu.harvard.CS50`, but I'll keep searching and ask.

**Comment by kzidane** [comment]
@dmalan, would having students call static function to init be of interest?

**Comment by dmalan** [comment]
Ah, interesting. Adding an `init` function feels like it adds an unnecessary, though we could take a bit of liberty and simply expect that buffering is disabled only if a student (1) imports the library and (2) calls at least one of our (already static) methods? Not quite as clever as simply #including `cs50.h` but pretty close?

**Comment by kzidane** [comment]
I don't see contradictory scenarios meanwhile, so gonna go with this for now.

**Comment by kzidane** [comment]
Disabled per #10!
